services:
  backend:
    image: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: .     

        # https://docs.docker.com/compose/intro/features-uses/
        # https://orm.drizzle.team/docs/guides/postgresql-local-setup
        # https://github.com/docker-library/docs/blob/master/postgres/README.md 