services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

        # https://docs.docker.com/compose/intro/features-uses/
        # https://orm.drizzle.team/docs/guides/postgresql-local-setup
        # https://github.com/docker-library/docs/blob/master/postgres/README.md 